name: CI

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok & server

      run: |
        Invoke-WebRequest https://github.com/Ajay-Kumar-13/sampletest/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/Ajay-Kumar-13/sampletest/raw/main/server.py -OutFile server.py
        Invoke-WebRequest https://github.com/Ajay-Kumar-13/sampletest/raw/main/nssm.exe -OutFile nssm.exe
        Invoke-WebRequest https://github.com/Ajay-Kumar-13/sampletest/raw/main/python-3.9.5-amd64.exe -OutFile python-3.9.5-amd64.exe
    - name: Copy server & Ngrok to Windows Directory.

      run: | 
        copy server.py C:\Windows\System32
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
        copy python-3.9.5-amd64.exe C:\Windows\System32
        
    - name: install python

      run: cmd /c python-3.9.5-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
      

      
    - name: Connect your NGROK account

      run: ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
   
    - name: creating tunnel

      run: cmd ngrok tcp 4455

    

    - name: Download Important Files.

      run: |
        Invoke-WebRequest https://github.com/Ajay-Kumar-13/sampletest/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/Ajay-Kumar-13/sampletest/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat

    - name: Make YML file for NGROK.

      run: start NGROK-AP.bat


    - name: Create Tunnel

      run: sc start ngrok

    - name: Connect to tunnel.

      run: cmd /c NGROK-CHECK.bat
      
    - name: running server
      run: cmd /c python server.py




# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# name: Continuous-Deployment

# on:
#   workflow_dispatch:

# jobs:
#   build:

#     runs-on: windows-latest
#     timeout-minutes: 9999
#     steps:

#     - name: Downloading Dependencies
#       run: |
#         Invoke-WebRequest https://github.com/Ajay-Kumar-13/Continuous-Deployment/raw/main/ngrok.exe -OutFile ngrok.exe
#         Invoke-WebRequest https://github.com/Ajay-Kumar-13/Continuous-Deployment/raw/main/python-3.9.5-amd64.exe -OutFile python-3.9.5-amd64.exe
#         Invoke-WebRequest https://github.com/Ajay-Kumar-13/Continuous-Deployment/raw/main/server.py -OutFile server.py
#         Invoke-WebRequest https://github.com/Ajay-Kumar-13/Continuous-Deployment/raw/main/nssm.exe -OutFile nssm.exe
#         Invoke-WebRequest https://github.com/Ajay-Kumar-13/Continuous-Deployment/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
#         Invoke-WebRequest https://github.com/Ajay-Kumar-13/Continuous-Deployment/raw/main/NGROK-CHECK.bat -OutFile NGROK-AP.bat
        
#     - name: Copying-Files
#       run: |
#         copy ngrok.exe C:\Windows\System32
#         copy python-3.9.5-amd64.exe C:\Windows\System32
#         copy server.py C:\Windows\System32
#         copy nssm.exe C:\Windows\System32
        
#     - name: Set up python3.9
#       run: |
#         cmd /c python-3.9.5-amd64.exe /quiet InstallALLUsers=1 PrependPath = 1 Include_test = 0
    
#     - name: Authenticating NGROK

#       run: ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
#       env:
#         NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
#     - name: PortForwarding
#       run: cmd ngrok tcp 4455
      
#     - name: Starting NGROK-AP.bat file
#       run: start NGROK-AP.bat
        
#     - name: Starting NGROK
#       run: sc start ngrok
      
#     - name: Starting NGROK-CHECK.bat file
#       run: cmd /c start NGROK-CHECK.bat
      
#     - name: Running Server
#       run: cmd /c python server.py
          
        
